version: '3.4'

x-network:
  &network
  networks:
    - api_platform_ssr

services:
  traefik:
    image: traefik
    command:
      - --api
      - --docker
      - --loglevel=DEBUG
      - --accessLog.filePath=/var/log/traefik/access.log
      - --accessLog.filters.statusCodes=404
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./log:/var/log
      - ./acme.json:/acme.json
    <<: *network

  fail2ban:
    image: alpine:latest
    build:
      context: .
      dockerfile: ./Dockerfile-fail2ban
    env_file:
      - ./fail2ban.env
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./log:/var/log:ro
      - ./data:/data

networks:
  api_platform_ssr:
    external: true
