version: '3.4'
services:
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    environment:
      - CF_API_KEY=${KEY}
      - CF_API_EMAIL=${EMAIL}
    networks:
      - api_platform_ssr
      - cheatuniverse_darkweak
      - cv
      - fire
      - marketplace_darkweak

networks:
  api_platform_ssr:
    external: true
  cheatuniverse_darkweak:
    external: true
  cv:
    external: true
  fire:
    external: true
  marketplace_darkweak:
    external: true
