[providers.docker]
  endpoint = "unix:///var/run/docker.sock"

[api]
  insecure = true
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"

[accessLog]
  filePath = "/var/log/traefik/access.log"
  [accessLog.filters]
    statusCodes = "404"

#[certificatesResolvers.sample.acme]
#  email = "youremail@domain.com"
#  storage = "acme.json"
#  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
#  [certificatesResolvers.sample.acme.httpChallenge]
#  [acme.httpChallenge]
#    entryPoint = "web"
